### PR TITLE
catch sqlite3.Error

### PR DESCRIPTION
**Pull request by maxbachmann**
I think we should directly catch sqlite3.Error instead of all Exceptions.

### CODE REVIEW

**Comment by maxbachmann** [comment]
btw the raise Exception calls should be replaced I guess.

**Comment by maxbachmann** [comment]
what other exceptions can occur?

**Comment by Psychokiller1888** [comment]
In these cases I guess you are correct, it's only treating sql stuff, sry

**Comment by maxbachmann** [comment]
another exception that could be thrown would be when e.g. the query is no string, but I think it is fine when this misuse throws

**Pull request merged**
