### PR TITLE
use github actions as ci

### PR DESCRIPTION
**Pull request by maxbachmann**

### CODE REVIEW

**Comment by Psychokiller1888** [comment]
Good stuff!

**Comment by maxbachmann** [comment]
yeah replaces travis completely and is a lot faster. Travis sometimes takes soooooooooooo long until it starts xD

**Comment by Psychokiller1888** [comment]
Oh, it's completly replacing travis? Didn't know that

**Comment by maxbachmann** [comment]
no I mean we can completely replace travis for our stuff

**Comment by Psychokiller1888** [comment]
Good!

**Comment by Psychokiller1888** [comment]
Wow, processed in 11 seconds, that's much faster in fact!

**Comment by maxbachmann** [comment]
yeah with travis it can take minutes until they finally start your build

**Pull request merged**
